
StructPtrTable_{AREA}:
    .word Structure00_{AREA}
    .word Structure01_{AREA}
    .word Structure02_{AREA}
    .word Structure03_{AREA}
    .word Structure04_{AREA}
    .word Structure05_{AREA}
    .word Structure06_{AREA}
    .word Structure07_{AREA}
    .word Structure08_{AREA}
    .word Structure09_{AREA}
    .word Structure0A_{AREA}
    .word Structure0B_{AREA}
    .word Structure0C_{AREA}
    .word Structure0D_{AREA}
    .word Structure0E_{AREA}
    .word Structure0F_{AREA}
    .word Structure10_{AREA}
    .word Structure11_{AREA}
    .word Structure12_{AREA}
    .word Structure13_{AREA}
    .word Structure14_{AREA}
    .word Structure15_{AREA}
    .word Structure16_{AREA}
    .word Structure17_{AREA}
    .word Structure18_{AREA}
    .word Structure19_{AREA}
    .word Structure1A_{AREA}
    .word Structure1B_{AREA}
    .word Structure1C_{AREA}
