    .word $C997
    .word $C9AA
    .word $C9B1
    .word $C9B8
    .word $C9D1
    .word $C9D5
    .word $C9DA
    .word $C9DF
    .word $C9EF
    .word $CA04
    .word $CA0A
    .word $CA15
    .word $CA2F
    .word $CA3C
    .word $CA45
    .word $CA50
    .word $CA5B
    .word $CA5E
    .word $CA64
    .word $CA6E
    .word $CA83
    .word $CA9F
    .word $CAAA
    .word $CAB1
    .word $CAC6
    .word $CAE2
    .word $CAE9
    .word $CAF2
    .word $CAF5
