    .word $CC89
    .word $CC9C
    .word $CCB5
    .word $CCCE
    .word $CCD5
    .word $CCDC
    .word $CCE0
    .word $CCE6
    .word $CCF6
    .word $CCFB
    .word $CD01
    .word $CD09
    .word $CD1E
    .word $CD27
    .word $CD31
    .word $CD3C
    .word $CD48
    .word $CD4B
    .word $CD55
    .word $CD58
    .word $CD6C
    .word $CD81
    .word $CD87
    .word $CD8D
    .word $CD96
    .word $CD9F
    .word $CDB2
    .word $CDC7
    .word $CDDC
    .word $CDED
    .word $CDF3
    .word $CDF6
    .word $CDFF
    .word $CE0A
    .word $CE10
    .word $CE25
    .word $CE29
    .word $CE34
    .word $CE3D
    .word $CE52
    .word $CE55
    .word $CE5E
    .word $CE61
    .word $CE64
    .word $CE6A
    .word $CE77
    .word $CE81
    .word $CE96
    .word $CEA9
