
RoomPtrTable_{AREA}: ;($C3AE)
    .word Room00_{AREA}
    .word Room01_{AREA}
    .word Room02_{AREA}
    .word Room03_{AREA}
    .word Room04_{AREA}
    .word Room05_{AREA}
    .word Room06_{AREA}
    .word Room07_{AREA}
    .word Room08_{AREA}
    .word Room09_{AREA}
    .word Room0A_{AREA}
    .word Room0B_{AREA}
    .word Room0C_{AREA}
    .word Room0D_{AREA}
    .word Room0E_{AREA}
    .word Room0F_{AREA}
    .word Room10_{AREA}
    .word Room11_{AREA}
    .word Room12_{AREA}
    .word Room13_{AREA}
    .word Room14_{AREA}
    .word Room15_{AREA}
    .word Room16_{AREA}
    .word Room17_{AREA}
    .word Room18_{AREA}
    .word Room19_{AREA}
    .word Room1A_{AREA}
    .word Room1B_{AREA}
    .word Room1C_{AREA}
    .word Room1D_{AREA}
    .word Room1E_{AREA}
    .word Room1F_{AREA}
    .word Room20_{AREA}
    .word Room21_{AREA}
    .word Room22_{AREA}
    .word Room23_{AREA}
    .word Room24_{AREA}
    .word Room25_{AREA}
    .word Room26_{AREA}
    .word Room27_{AREA}
    .word Room28_{AREA}
    .word Room29_{AREA}
    .word Room2A_{AREA}
    .word Room2B_{AREA}
    .word Room2C_{AREA}
    .word Room2D_{AREA}
    .word Room2E_{AREA}

