
    .word $CC5C
    .word $CC6F
    .word $CC88
    .word $CCA1
    .word $CCA8
    .word $CCAF
    .word $CCB3
    .word $CCBE
    .word $CCCB
    .word $CCD7
    .word $CCDD
    .word $CCE2
    .word $CCF2
    .word $CCF6
    .word $CD00
    .word $CD25
    .word $CD2F
    .word $CD42
    .word $CD57
    .word $CD66
    .word $CD70
    .word $CD7A
    .word $CD85
    .word $CD96
    .word $CDBB
    .word $CDBE
    .word $CDC4
    .word $CDD1
    .word $CDE1
    .word $CDEB
    .word $CDF0
    .word $CE05
    .word $CE1A
    .word $CE20
    .word $CE23
    .word $CE37
    .word $CE48
    .word $CE5D
    .word $CE66
    .word $CE6A
    .word $CE7D
    .word $CE88
    .word $CE8B
    .word $CE96
    .word $CEA0
    .word $CEA3
    .word $CEB6
    .word $CEB9
    .word $CEBC
    .word $CEC5

