    .word $CA43
    .word $CA56
    .word $CA6F
    .word $CA88
    .word $CA8F
    .word $CA96
    .word $CA9A
    .word $CAAA
    .word $CABA
    .word $CABF
    .word $CAC4
    .word $CAC7
    .word $CACA
    .word $CAD5
    .word $CADB
    .word $CAE0
    .word $CAE9
    .word $CAFE
    .word $CB01
    .word $CB14
    .word $CB29
    .word $CB2D
    .word $CB40
    .word $CB4D
    .word $CB60
    .word $CB73
    .word $CB88
    .word $CB92
    .word $CB95
    .word $CB9C
    .word $CBB8
    .word $CBC1
    .word $CBD6
    .word $CBD9
    .word $CBE2
    .word $CBE7
    .word $CBEC
    .word $CBF6
    .word $CBFF
