    .word $CC6B
    .word $CC7E
    .word $CCA5
    .word $CCBE
    .word $CCC5
    .word $CCCC
    .word $CCCF
    .word $CCE0
    .word $CCF9
    .word $CD0A
    .word $CD1B
    .word $CD25
    .word $CD4E
    .word $CD7B
    .word $CD82
    .word $CD91
    .word $CD94
    .word $CD9D
    .word $CDB6
    .word $CDBB
    .word $CDC0
    .word $CDEE
    .word $CE01
    .word $CE1D
    .word $CE32
    .word $CE53
    .word $CE64
    .word $CE6F
    .word $CE73
    .word $CE76
    .word $CE81
    .word $CE8B
